jwt:
  secret: ${env.JWT_SECRET}

spring:
  cloud:
    gcp:
      sql:
        enabled: false
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${env.SQL_SERVER}
    username: debian-sys-maint
    password: ${env.DATA_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver